api_url: https://image-api.photoroom.com/v2/edit
api_key: sandbox_sk_pr_default_2a803e41fabca177d19f0c08a4b2bd8f9e711cfa
#api_key: sk_pr_default_07394c5dda2a50ccbe1efbfaf3b820bf2414194e
#api_key: sandbox_sk_pr_default_07394c5dda2a50ccbe1efbfaf3b820bf2414194e